spring:
  application:
    name: USER-SERVICE
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/eurekauser?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    jpa:
      hibernate:
        ddl-auto: update #운영시에는 validate 추천s

      show-sql: true
    driver-class-name: com.mysql.jdbc.Driver
  # JWT Secret Key
  jwt:
<<<<<<< HEAD
    secret: kimsungshilkimsungshilkimsungshilkimsungshilkimsungshilkimsungshilkimsungshil
  #Redis
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    timeout: 0
=======
    secret : kimsungshilkimsungshilkimsungshilkimsungshilkimsungshilkimsungshilkimsungshil

<<<<<<< backend/User/src/main/resources/application.yml
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
=======
>>>>>>> a5d6b9746a8060369aa07a14ed58bd04ffdf5525

>>>>>>> backend/User/src/main/resources/application.yml










