server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: GATEWAY-SERVICE
zuul:
  routes:
    AUTH-SERVICE:
      path: /login/**
      stripPrefix: false
    FACE-SERVICE:
      path: /face/**
      stripPrefix: false
    seller-service:
      path: /seller/**
      serviceId: SELLER-SERVICE
      stripPrefix: false
    store-service:
      path: /store/**
      serviceId: SELLER-SERVICE
      stripPrefix: false
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
