server:
  port: 9999
  ssl:
    enabled: true
    key-store: /home/test/eureka_keystore.jks
    key-store-password: wndeowkd
    key-password: wndeowkd
    key-alias: eureka
    trust-store: /home/test/eureka_truestore.ts
    trust-store-password: wndeowkd

    security.require-ssl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafy?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: sumin
    password: sumin
  application:
    name: AUTH-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
